name: .NET API Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "RSVP-Tracker/api/**"

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: RSVP-Tracker/api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build the API Project
      run: dotnet build --no-restore

    - name: Run Unit & Integration Tests
      run: dotnet test --no-build --verbosity normal
