name: .NET API Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "*/api/**"

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build the API Project
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit & Integration Tests
        run: dotnet test --no-build --configuration Release --verbosity normal
