name: .NET API Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Path Filters
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'api/**'

      # Early Exit if No Changes in API Directory
      - name: Skip Workflow (No API Changes)
        if: steps.filter.outputs.api != 'true'
        run: |
          echo "No changes in 'api/'. Skipping workflow."
          exit 0

      - name: Setup .NET
        if: steps.filter.outputs.api == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        if: steps.filter.outputs.api == 'true'
        run: dotnet restore

      - name: Build the API Project
        if: steps.filter.outputs.api == 'true'
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit & Integration Tests
        if: steps.filter.outputs.api == 'true'
        run: dotnet test --no-build --configuration Release --verbosity normal
