name: .NET Code Formatting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
